# Generated by Django 4.0.5 on 2023-11-20 15:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0022_alter_customuser_birthday_alter_customuser_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='カテゴリ')),
                ('set_value', models.CharField(max_length=30, verbose_name='設定値')),
            ],
        ),
        migrations.CreateModel(
            name='ExBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('first_name', models.CharField(max_length=30, verbose_name='姓')),
                ('last_name', models.CharField(max_length=30, verbose_name='名')),
                ('sex', models.IntegerField(default=0)),
                ('age', models.CharField(default=0, max_length=3)),
                ('people', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('email_ch', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス確認')),
                ('tel_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='右の形式で入力してください「090-1234-5678」', regex='^0\\d{1,4}-\\d{1,4}-\\d{3,4}$/')], verbose_name='携帯電話番号')),
                ('objective', models.CharField(max_length=30, verbose_name='目的')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='伝えたいこと')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.training', verbose_name='トレーニング')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('booking_count', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, default='', verbose_name='備考')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='accounts.training', verbose_name='トレーニング')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
