# Generated by Django 4.0.5 on 2024-06-28 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0026_customuser_email_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(default='default@example.com', max_length=254, verbose_name='送信元メールアドレス')),
                ('site_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='開始時間')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='終了時間')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='姓')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='名')),
                ('sex', models.IntegerField(default=0, null=True)),
                ('age', models.CharField(default=0, max_length=3, null=True)),
                ('people', models.IntegerField(default=0, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('tel_number', models.CharField(max_length=15, null=True, verbose_name='携帯電話番号')),
                ('objective', models.CharField(max_length=30, null=True, verbose_name='目的')),
                ('remarks', models.TextField(default='', null=True, verbose_name='伝えたいこと')),
                ('url_param', models.CharField(default='default', max_length=10, null=True, verbose_name='url_param')),
                ('status', models.CharField(default=0, max_length=1, verbose_name='ステータス')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='有効期限')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.training', verbose_name='トレーニング')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('training_no', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='', verbose_name='備考')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('del_flg', models.IntegerField(default=0)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='accounts.training', verbose_name='トレーニング')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
