# Generated by Django 4.0.5 on 2024-06-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbooking',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='exbooking',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='開始時間'),
        ),
    ]
