# Generated by Django 4.0.5 on 2024-06-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0002_alter_exbooking_end_alter_exbooking_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbooking',
            name='url_param',
            field=models.CharField(default='wwFaGxlPBX', max_length=10, null=True, verbose_name='url_param'),
        ),
    ]
