# Generated by Django 4.0.5 on 2024-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0003_alter_exbooking_url_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbooking',
            name='url_param',
            field=models.CharField(default='80EJ4HS6qF', max_length=10, null=True, unique=True, verbose_name='url_param'),
        ),
    ]
