# Generated by Django 4.0.5 on 2024-06-28 13:44

import app.app_member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0004_alter_exbooking_url_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbooking',
            name='url_param',
            field=models.CharField(default=app.app_member.models.generate_random_string, max_length=10, null=True, unique=True, verbose_name='url_param'),
        ),
    ]
