# Generated by Django 4.0.5 on 2024-07-02 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0005_alter_exbooking_url_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='exbooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='有効期限'),
        ),
        migrations.AddField(
            model_name='exbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='exbooking',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
