# Generated by Django 4.0.5 on 2024-07-02 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0006_exbooking_created_at_exbooking_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成時間'),
        ),
    ]
