# Generated by Django 4.0.5 on 2024-07-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0007_alter_exbooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exbooking',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='有効フラグ', verbose_name='有効'),
        ),
    ]
