# Generated by Django 4.0.5 on 2024-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0008_exbooking_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exbooking',
            name='updated_app',
            field=models.DateTimeField(auto_now=True, verbose_name='更新アプリ'),
        ),
    ]
