# Generated by Django 4.0.5 on 2024-11-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0009_exbooking_updated_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exbooking',
            name='updated_app',
        ),
    ]
