# Generated by Django 4.0.5 on 2024-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0010_remove_exbooking_updated_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='exbooking',
            name='updated_app',
            field=models.CharField(max_length=30, null=True, verbose_name='更新アプリ'),
        ),
    ]
