# Generated by Django 4.0.5 on 2024-12-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0011_exbooking_updated_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exbooking',
            old_name='updated_app',
            new_name='updated_by',
        ),
    ]
