# Generated by Django 4.0.5 on 2024-12-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0012_rename_updated_app_exbooking_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbooking',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
