# Generated by Django 4.0.5 on 2025-01-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0014_booking_created_at_emailtemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='shop_tel1',
            field=models.CharField(max_length=15, null=True, verbose_name='お店電話番号1'),
        ),
    ]
