# Generated by Django 4.0.5 on 2025-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_member', '0015_master_shop_tel1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='site_url',
            field=models.URLField(blank=True, null=True, verbose_name='サイトURL'),
        ),
    ]
