# Generated by Django 4.0.5 on 2022-11-06 07:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_training_display_num'),
        ('app', '0004_booking_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('first_name', models.CharField(max_length=30, verbose_name='姓')),
                ('last_name', models.CharField(max_length=30, verbose_name='名')),
                ('sex', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('people', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('tel_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='右の形式で入力してください「090-1234-5678」', regex='^0\\d{1,4}-\\d{1,4}-\\d{3,4}$/')], verbose_name='携帯電話番号')),
                ('objective', models.CharField(max_length=30, verbose_name='目的')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='伝えたいこと')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.training', verbose_name='トレーニング')),
            ],
        ),
    ]
