# Generated by Django 4.0.5 on 2022-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_exbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbooking',
            name='age',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
