# Generated by Django 4.0.5 on 2022-11-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='master',
        ),
    ]
