# Generated by Django 4.0.5 on 2022-11-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbooking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='メールアドレス'),
        ),
    ]
