# Generated by Django 4.0.5 on 2022-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_exbooking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='exbooking',
            name='email_ch',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス確認'),
        ),
    ]
