# Generated by Django 4.0.5 on 2023-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notice',
            field=models.TextField(blank=True, default='', verbose_name='おしらせ'),
        ),
    ]
