# Generated by Django 4.0.5 on 2022-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='experience_flg',
            field=models.IntegerField(default=0, verbose_name='体験フラグ'),
        ),
    ]
