# Generated by Django 4.0.5 on 2022-10-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_training_experience_flg'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='display_num',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
    ]
