# Generated by Django 4.0.5 on 2022-12-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_training_display_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duplicates_num',
            field=models.IntegerField(default=1, verbose_name='重複数'),
        ),
    ]
