# Generated by Django 4.0.5 on 2023-04-11 13:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_training_duplicates_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone3',
        ),
        migrations.AddField(
            model_name='customuser',
            name='amount_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='end_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_shoes_custody',
            field=models.BooleanField(default=False, help_text='靴預り', verbose_name='shoes_custody'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='右の形式で入力してください「090-1234-5678」', regex='^0\\d{1,4}-\\d{1,4}-\\d{3,4}$/')], verbose_name='携帯電話番号'),
        ),
    ]
