# Generated by Django 4.0.5 on 2023-04-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_phone1_remove_customuser_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='amount_money',
            field=models.IntegerField(default=0, verbose_name='口座引落金額'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_shoes_custody',
            field=models.BooleanField(default=False, help_text='靴預り', verbose_name='靴預り'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_times',
            field=models.IntegerField(default=0, verbose_name='回数'),
        ),
    ]
