# Generated by Django 4.0.5 on 2023-04-11 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_amount_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.IntegerField(default=0, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='右の形式で入力してください「090-1234-5678」', regex='[(]?\\d{2,4}[-)]?\\d{2,4}-\\d{3,4}')], verbose_name='携帯電話番号'),
        ),
    ]
