# Generated by Django 4.0.5 on 2023-04-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_sex_alter_customuser_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='このユーザーを停止させたい場合はチェックを外してください', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='スタッフの場合はチェックを入れてください', verbose_name='staff status'),
        ),
    ]
