# Generated by Django 4.0.5 on 2023-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_is_active_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_shoes_custody',
            field=models.BooleanField(default=False, help_text='靴預りありの場合はチェックを入れてください', verbose_name='靴預り'),
        ),
    ]
