# Generated by Django 4.0.5 on 2023-04-11 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_is_shoes_custody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='生年月日'),
        ),
    ]
