# Generated by Django 4.0.5 on 2023-04-11 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='入会日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='end_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='開始日'),
        ),
    ]
