# Generated by Django 4.0.5 on 2023-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_birthday_alter_customuser_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_contracts',
            field=models.IntegerField(default=0, verbose_name='契約回数'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_times',
            field=models.IntegerField(default=0, verbose_name='予約残回数'),
        ),
    ]
