# Generated by Django 4.0.5 on 2023-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_num_contracts_alter_customuser_num_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='num_contracts',
            field=models.IntegerField(default=8, verbose_name='契約回数'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_times',
            field=models.IntegerField(default=8, verbose_name='予約残回数'),
        ),
    ]
