# Generated by Django 4.0.5 on 2023-04-12 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_num_contracts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='end_end',
        ),
        migrations.AddField(
            model_name='customuser',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='契約終了日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='契約開始日'),
        ),
    ]
