# Generated by Django 4.0.5 on 2023-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_no',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='会員番号'),
        ),
    ]
