# Generated by Django 4.0.5 on 2023-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_member_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='withdrawal',
            field=models.BooleanField(default=False, help_text='退会の場合はチェックを入れてください', verbose_name='退会'),
        ),
    ]
