# Generated by Django 4.0.5 on 2023-07-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customuser_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='withdrawal',
        ),
    ]
