# Generated by Django 4.0.5 on 2023-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_customuser_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateField(blank=True, null=True, verbose_name='入会日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='契約終了日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.IntegerField(default=2, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_date',
            field=models.DateField(blank=True, null=True, verbose_name='契約開始日'),
        ),
    ]
