# Generated by Django 4.0.5 on 2023-12-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customuser_birthday_alter_customuser_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='del_flg',
            field=models.BooleanField(default=True, help_text='このトレーニングを停止させたい場合はチェックを外してください', verbose_name='active'),
        ),
    ]
