# Generated by Django 4.0.5 on 2023-12-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_training_del_flg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='del_flg',
            new_name='is_active',
        ),
    ]
