# Generated by Django 4.0.5 on 2023-12-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_del_flg_training_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='is_active',
        ),
        migrations.AddField(
            model_name='training',
            name='del_flg',
            field=models.IntegerField(default=0, verbose_name='削除フラグ'),
        ),
    ]
