# Generated by Django 4.0.5 on 2023-08-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='おしらせ')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=31, verbose_name='姓')),
                ('last_name', models.CharField(max_length=31, verbose_name='名')),
                ('is_active', models.BooleanField(default=True, help_text='このユーザーを停止させたい場合はチェックを外してください', verbose_name='active')),
            ],
        ),
    ]
