# Generated by Django 4.0.5 on 2023-09-14 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0002_staff_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='備考')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_staff.staff', verbose_name='スタッフ仕事')),
            ],
        ),
    ]
