# Generated by Django 4.0.5 on 2023-10-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0004_rename_staff_staffwork_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffwork',
            name='end',
            field=models.DateTimeField(auto_now_add=True, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='staffwork',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='開始時間'),
        ),
    ]
