# Generated by Django 4.0.5 on 2023-11-03 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0005_alter_staffwork_end_alter_staffwork_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffwork',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='staffwork',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
        ),
    ]
