# Generated by Django 4.0.5 on 2024-01-16 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_training_is_active_training_del_flg'),
        ('app_staff', '0006_alter_staffwork_end_alter_staffwork_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1, verbose_name='タイプ')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('training_no', models.IntegerField(default=0)),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.training', verbose_name='トレーニング')),
            ],
        ),
    ]
