# Generated by Django 4.0.5 on 2024-01-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0007_closingday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closingday',
            name='type',
        ),
        migrations.AddField(
            model_name='closingday',
            name='closing_type',
            field=models.CharField(default=None, max_length=1, verbose_name='休日タイプ'),
        ),
    ]
