# Generated by Django 4.0.5 on 2024-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0008_remove_closingday_type_closingday_closing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingday',
            name='training_no',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
