# Generated by Django 4.0.5 on 2024-12-21 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_staff', '0010_staffwork_created_at_staffwork_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingday',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成時間'),
        ),
        migrations.AddField(
            model_name='closingday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成時間'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成時間'),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
